wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret ap_password

api:
  password: !secret api_password
  encryption:
    key: !secret api_key
ota:
  password: !secret ota_password

captive_portal:

# Enable logging
logger:
